community_management/com/urls.py
from django.urls import path, include, re_path
from com.views import account, home

urlpatterns = [
    # 用户
    path('user_login/', account.user_login, name='user_login'),
    path('user_register/', account.user_register, name='user_register'),
    path('login_out/', account.login_out, name='login_out'),
    path('ajax_change_files/', account.ajax_change_icon_view, name='ajax_change_files'),
    # 首页
    path('home/', home.home, name='home'),
    # 图书详情
    path('com_detail/', home.com_detail, name='com_detail'),
    # 评论
    path('comment/', home.comment, name='comment'),
    # 收藏
    path('add_collection/', home.add_collection, name='add_collection'),

    # 申请
    path('apply_for/', home.apply_for, name='apply_for'),
    # 收藏
    path('com_shelf/', home.com_shelf, name='com_shelf'),
    # 申请记录
    path('apply_reg/', home.apply_reg, name='apply_reg'),

]

community_management/community_management/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    # 社团
    path('com/', include('com.urls')),
    path('com_admin/', include('com_admin.urls')),

    # 图片
    re_path(r'media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
]

community_management/com/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

from utils.models import BaseModel


class UserInfo(AbstractUser):
    """用户模型类"""
    user_type_choices = (
        (1, '用户'),
        (2, '管理员')
    )

    # 用户类型
    user_type = models.SmallIntegerField(verbose_name='用户类型', choices=user_type_choices, default=1)
    # 手机号
    telephone = models.CharField(max_length=11, verbose_name='手机号码', null=True, blank=True)
    avatar = models.ImageField(upload_to="avatar", verbose_name="头像图片", default='avatar/avatar.jpg')
    addr = models.TextField(verbose_name='学生来源', null=True, blank=True)
    community = models.ForeignKey(verbose_name='社团', to="Community", on_delete=models.DO_NOTHING, db_constraint=False,
                                  related_name='u_com', null=True, blank=True)

    class Meta:
        db_table = 'com_userinfo'  # 创建的表名，如果不写，默认app_userinfo
        # 下面两个是配套的，用来在admin中表名显示汉字
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class Community(BaseModel):
    """
    社团
    """
    name = models.CharField(verbose_name='社团名称', null=True, blank=True, max_length=225)
    # 12
    com_img = models.ImageField(upload_to="com", verbose_name="社团图片", default='com/com.jpg')
    desc = models.TextField(verbose_name='更多介绍', null=True, blank=True)

    hot = models.FloatField(verbose_name='热度', default=0.00528)
    community_type = models.ForeignKey(verbose_name='社团类型', to="Community_Type", on_delete=models.DO_NOTHING,
                                       db_constraint=False,
                                       related_name='c_ct', null=True, blank=True)

    class Meta:
        db_table = 'com_community'  # 创建的表名，如果不写，默认app_userinfo
        # 下面两个是配套的，用来在admin中表名显示汉字
        verbose_name = '社团'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Community_Type(BaseModel):
    """
    社团类型
    """
    name = models.CharField(verbose_name='分类名称', max_length=64)

    class Meta:
        db_table = 'com_community_type'  # 创建的表名，如果不写，默认app_userinfo
        # 下面两个是配套的，用来在admin中表名显示汉字
        verbose_name = '社团分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Comment(BaseModel):
    """
    评论
    """
    """评论表"""
    comment = models.CharField(verbose_name='评论内容', max_length=225, null=True, blank=True)
    userinfo = models.ForeignKey(verbose_name='用户', to=UserInfo, on_delete=models.DO_NOTHING, db_constraint=False,
                                 null=True, blank=True, related_name='comment_userinfo')

    reply = models.ForeignKey(verbose_name='父评论', to='self', on_delete=models.DO_NOTHING, db_constraint=False,
                              null=True, blank=True, related_name='comment_reply')

    depth = models.PositiveIntegerField(verbose_name='评论深度', default=1)

    root = models.PositiveIntegerField(verbose_name='父id', null=True, blank=True)
    community = models.ForeignKey(verbose_name='社团', to='Community', on_delete=models.DO_NOTHING,
                                  db_constraint=False, related_name='c_b')

    class Meta:
        db_table = "com_comment"


class Com_Shelf(BaseModel):
    """
    收藏
    """
    community = models.ForeignKey(verbose_name='社团', to='Community', on_delete=models.DO_NOTHING, db_constraint=False,
                                  related_name='cs_c', null=True, blank=True)
    userinfo = models.ForeignKey(verbose_name='用户', to=UserInfo, on_delete=models.DO_NOTHING, db_constraint=False,
                                 related_name='cs_u', null=True, blank=True)
    is_start = models.BooleanField(verbose_name='收藏字段', default=False)


class Apply(BaseModel):
    """
    申请记录
    """
    apply_type_choices = (
        (1, '未处理'),
        (2, '同意'),
        (3, '拒绝'),
        (4, '剔除'),
    )
    community = models.ForeignKey(verbose_name='社团', to='Community', on_delete=models.DO_NOTHING, db_constraint=False,
                                  related_name='ap_c', null=True, blank=True)
    userinfo = models.ForeignKey(verbose_name='用户', to=UserInfo, on_delete=models.DO_NOTHING, db_constraint=False,
                                 related_name='ap_u', null=True, blank=True)
    apply_type = models.SmallIntegerField(verbose_name='进度', choices=apply_type_choices, default=1)

    class Meta:
        db_table = 'com_apply'  # 创建的表名，如果不写，默认app_userinfo
        # 下面两个是配套的，用来在admin中表名显示汉字
        verbose_name = '申请记录'
        verbose_name_plural = verbose_name


class Active(BaseModel):
    """
    活动
    """
    name = models.CharField(verbose_name='活动名称', max_length=64, null=True, blank=True)
    community = models.ForeignKey(verbose_name='社团', to='Community', on_delete=models.DO_NOTHING, db_constraint=False,
                                  related_name='act_c', null=True, blank=True)
    desc = models.TextField(verbose_name='活动介绍', max_length=64, null=True, blank=True)

    class Meta:
        db_table = 'com_active'  # 创建的表名，如果不写，默认app_userinfo
        # 下面两个是配套的，用来在admin中表名显示汉字
        verbose_name = '活动'
        verbose_name_plural = verbose_name

community_management/com/views/account.py
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from com import models
from utils.md5 import md5


def user_register(request):
    """
    注册
    :param request:
    :return:
    """
    if request.method == 'GET':
        return render(request, 'user/register.html')
    form_error = '账号错误或密码错误'

    username = request.POST.get('username')
    password = request.POST.get('password')
    data = {
        'username': username,
        'password': md5(password),
    }
    print('data', data)
    if not username or not password:
        return render(request, 'user/register.html', locals())
    exist = models.UserInfo.objects.filter(username=username).exists()
    if exist:
        form_error = '用户名已存在'
        return render(request, 'user/register.html', locals())
    try:
        models.UserInfo.objects.create(**data)
        return redirect('user_login')
    except Exception:
        form_error = '创建失败,信息不合法'
        return render(request, 'user/register.html', locals())


def user_login(request):
    """
    登录
    :param request:
    :return:
    """
    if request.method == 'GET':
        return render(request, 'user/login.html')

    form_error = '账号错误或密码错误'

    # 查询当前用户是否存在
    username = request.POST.get('username')
    password = request.POST.get('password')
    # print(username)
    # print(password)
    # 查询当前用户是否存在
    user_query = models.UserInfo.objects.filter(username=username, password=md5(password), is_active=True)
    # 如果不存在
    if not user_query.exists():
        return render(request, 'user/login.html', {'form_error': form_error})
    # 修改状态
    user_obj = user_query.first()
    # 存session
    request.session['user_dic'] = {'id': user_obj.id, 'username': user_obj.username,
                                   'user_type': user_obj.user_type,
                                   'avatar': user_obj.avatar.url,
                                   'addr': user_obj.addr,
                                   'telephone': user_obj.telephone,
                                   }
    # /media/avatar/avatar.jpg
    # print(user_obj.avatar)
    # print(request.session.get('user_dic').get('user_type'))
    return redirect('home')


def login_out(request):
    """
    退出
    :param request:
    :return:
    """
    # 退出
    user_id = request.session.get('user_dic')['id']
    user_obj = models.UserInfo.objects.get(id=user_id)
    # print(user_obj, '------------')
    user_obj.is_login = False
    user_obj.save()
    # 清楚session
    request.session.clear()
    return redirect('user_login')


def ajax_change_icon_view(request):
    """
    个人信息修改
    :param request:
    :return:
    """
    user_id = request.session.get('user_dic')['id']

    user_obj = models.UserInfo.objects.get(id=user_id)

    # 获取新的图片对象
    new_img = request.FILES.get('icon')
    telephone = request.POST.get('telephone')
    addr = request.POST.get('addr')
    # print(telephone, '---------手机号')
    if new_img:
        user_obj.avatar = new_img
    if telephone:
        user_obj.telephone = telephone
    if addr:
        user_obj.addr = addr
    try:
        user_obj.save()
    except Exception:
        pass
    img_url = user_obj.avatar.url
    return JsonResponse({'status': 200, 'url': img_url})

community_management/com/views/home.py
from django.conf import settings
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect, HttpResponse

# Create your views here.
from com import models
from utils import page
from utils.md5 import md5


def home(request):
    """
    首页
    :param request:
    :return:
    """
    userinfo_id = request.session.get('user_dic').get('id')
    user_obj = models.UserInfo.objects.get(id=userinfo_id)
    print(user_obj.avatar)
    # 获取种类
    type_query = models.Community_Type.objects.filter(is_delete=False, is_active=True)
    # 获取热度最高的前3图书，
    hot = models.Community.objects.filter(is_delete=False, is_active=True).order_by('-hot', '-id')[
          settings.HOT_START:settings.HOT_END]
    hot_com = models.Community.objects.filter(is_delete=False, is_active=True).order_by('-hot', '-id').first()

    q = request.GET.get('q')
    # print(q)
    # 社团渲染
    if q:
        # print(q)

        # 查询数据+分页
        current_page = request.GET.get('page')
        page_object = page.Pagination(current_page=current_page,
                                      all_count=models.Community.objects.filter(
                                          Q(name__icontains=q) | Q(community_type__name=q),
                                          is_active=True,
                                          is_delete=False,
                                      ).count(),
                                      base_url=request.path_info,
                                      query_params=request.GET,
                                      per_page=settings.BOOK_NUM,
                                      )
        query = models.Community.objects.filter(Q(name__icontains=q) | Q(community_type__name=q), is_active=True,
                                                is_delete=False,
                                                ).order_by('-hot',
                                                           '-id').select_related(
            'community_type')[
                page_object.start:page_object.end]
        # print(query, '--------')
        page_html = page_object.page_html()

    else:
        current_page = request.GET.get('page')
        page_object = page.Pagination(current_page=current_page,
                                      all_count=models.Community.objects.filter(is_active=True,
                                                                                is_delete=False).count(),
                                      base_url=request.path_info,
                                      query_params=request.GET,
                                      per_page=settings.BOOK_NUM,
                                      )
        query = models.Community.objects.filter(is_active=True, is_delete=False).order_by('-hot',
                                                                                          '-id').select_related(
            'community_type')[
                page_object.start:page_object.end]
        # print(query, '--------')
        # for item in query:
        #     # print(item.community_type__name)
        #     print(item.community_type.all())
        page_html = page_object.page_html()
    return render(request, 'q_home/index.html', locals())


def com_detail(request):
    """
    社团详情
    :param request:
    :return:
    """
    # 社团
    id = request.GET.get('id')

    userinfo_id = request.session.get('user_dic').get('id')
    # 评论
    comment_query = models.Comment.objects.filter(community_id=id, is_active=True, is_delete=False)
    # 查询社团
    query = models.Community.objects.filter(id=id, is_delete=False, is_active=True).first()
    # 查询是否收藏过
    start_query = models.Com_Shelf.objects.filter(community_id=id, userinfo_id=userinfo_id, is_delete=False,
                                                  is_active=True)
    if start_query.exists():
        my_start = start_query.first().is_start
    else:
        my_start = ''
    # print(my_start, 'my_start')
    # print(query_book)
    # 热力值增加
    hot_num = settings.HOT_NUM
    query.hot = '%.5f' % (query.hot + ((1 + hot_num) * 1.000000001))
    query.save()
    # print(query.hot, 'new_hot_num')
    # 获取数量
    count = models.Apply.objects.filter(community_id=id, apply_type=1, is_active=True, is_delete=False).count()
    # 获取社团活动,获取最新的前三个
    active = models.Active.objects.filter(community_id=id, is_active=True, is_delete=False).order_by('-id')[0:3]
    return render(request, 'q_home/detail.html', locals())


def add_collection(request):
    """
    添加收藏
    :param request:
    :return:
    """
    data = {
        'status': 200
    }
    id = request.POST.get('id')
    userinfo_id = request.session.get('user_dic').get('id')
    # 第一个值是查到或者创建的数据，第二个值是一个布尔，表示是否执行了创建操作。创建为True，未创建为False
    obj, bol = models.Com_Shelf.objects.get_or_create(community_id=id, userinfo_id=userinfo_id, is_delete=False,
                                                      is_active=True)
    # 如果是新建的，肯定是收藏，修改is_start
    is_start = obj.is_start
    if is_start:
        obj.is_start = False
    else:
        obj.is_start = True
    obj.save()
    return JsonResponse(data)


def comment(request):
    """
    评论
    :param request:
    :return:


    """
    data = {

        'status': 200,
    }
    userinfo_id = request.session.get('user_dic').get('id')

    id = request.POST.get('id')
    # print(book_id)
    comment = request.POST.get('comment')

    comment = comment.strip()
    if not comment:
        data['status'] = 201
        return JsonResponse(data)
    userinfo = models.UserInfo.objects.get(id=userinfo_id)
    # 创建评论记录
    models.Comment.objects.create(comment=comment, userinfo=userinfo, depth=1, community_id=id)
    return JsonResponse(data)


def apply_for(request):
    """
    申请
    :param request:
    :return:
    """
    data = {

        'status': 200,
    }
    userinfo_id = request.session.get('user_dic').get('id')

    id = request.POST.get('id')
    # 第一个值是查到或者创建的数据，第二个值是一个布尔，表示是否执行了创建操作。创建为True，未创建为False
    obj, bol = models.Apply.objects.get_or_create(community_id=id, userinfo_id=userinfo_id)
    if bol:
        # 新建
        data['msg'] = '申请成功，请耐心等待'
    else:
        # 查询到了
        data['status'] = 201
        data['msg'] = '您已经申请过了，请耐心等待'

    return JsonResponse(data)


def com_shelf(request):
    """
    收藏
    :param request:
    :return:
    """
    userinfo_id = request.session.get('user_dic').get('id')
    query = models.Com_Shelf.objects.filter(userinfo_id=userinfo_id, is_delete=False, is_active=True,
                                            is_start=True).order_by(
        '-id').select_related('userinfo', 'community')
    return render(request, 'others/com_shelf.html', locals())


def apply_reg(request):
    """
    申请记录
    :param request:
    :return:
    """
    userinfo_id = request.session.get('user_dic').get('id')
    query = models.Apply.objects.filter(userinfo_id=userinfo_id, is_delete=False, is_active=True).order_by(
        '-id').select_related('userinfo', 'community')
    return render(request, 'others/apply_reg.html', locals())

community_management/com/templates/others/apply_reg.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
    <title>我的申请</title>
    <link rel="stylesheet" type="text/css" href="{% static 'others/css/style.css' %}"/>
</head>

<body>


<div class="section-news">
    <div class="wrapper">
        <div class="ei-title bar">
            <h1>我的申请</h1>
        </div>

        {% for field in query %}

            <div class="agent-body">
                <div class="news-body">
                    {#                <div class="news-pic-box"></div>#}
                    <div class="news-text">
                        <div class="news-text-content">
                            <ul>
                                <li>
                                    <div class="news-title-content">
                                        <h1 class="js-title"><a
                                                href="{% url 'com_detail' %}?id={{ field.community.id }}">{{ field.community.name }}</a>
                                        </h1>
                                        <p class="js-title">
                                            <a href="#">申请时间:{{ field.create_time }}</a>
                                        </p>
                                        <p class="js-title">
                                            <a href="#">社团类型:{{ field.community.community_type.name }}</a>
                                        </p>
                                        <p class="js-title">
                                            <a href="#" style="color: #08e50b">处理进度:{{ field.get_apply_type_display }}</a>
                                        </p>
                                    </div>
                                    <a class="cui-btn"
                                       href="{% url 'com_detail' %}?id={{ field.community.id }}">查看详情</a>
                                    <a class="cui-btn"
                                       href="{% url 'home' %}">返回首页</a>
                                </li>


                            </ul>
                            {#                        <div class="news-text-pagination">#}
                            {#                            <span class="swiper-pagination-bullet"></span><span class="swiper-pagination-bullet"></span><span#}
                            {#                                class="swiper-pagination-bullet"></span><span#}
                            {#                                class="swiper-pagination-bullet swiper-pagination-bullet-active"></span>#}
                            {#                        </div>#}
                        </div>
                    </div>

                </div>
            </div>

        {% endfor %}

    </div>
</div>

<!--jQuery框架库-->
<script src="{% static 'plugin/jquery-3.4.1/jquery-3.4.1.min.js' %}"></script>

<!--插件-->
<script src="{% static 'others/js/jquery.SuperSlide.2.1.3.js' %}" type="text/javascript" charset="utf-8"></script>

<!--调用方法-->
<script type="text/javascript">
    jQuery(".news-text").slide({
        mainCell: ".news-text-content ul",
        autoPlay: false,
        titCell: ".news-text-pagination span",
        trigger: "click",
        effect: "left"
    });
</script>

</body>
</html>

community_management/com/templates/others/com_shelf.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
    <title>我的收藏</title>
    <link rel="stylesheet" type="text/css" href="{% static 'others/css/style.css' %}"/>
</head>

<body>


<div class="section-news">
    <div class="wrapper">
        <div class="ei-title bar">
            <h1>我的收藏</h1>
        </div>

        {% for field in query %}

            <div class="agent-body">
                <div class="news-body">
                    {#                <div class="news-pic-box"></div>#}
                    <div class="news-text">
                        <div class="news-text-content">
                            <ul>
                                <li>
                                    <div class="news-title-content">
                                        <h1 class="js-title"><a
                                                href="{% url 'com_detail' %}?id={{ field.community.id }}">{{ field.community.name }}</a>
                                        </h1>
                                        <p class="js-title">
                                            <a href="#">收藏时间:{{ field.create_time }}</a>
                                        </p>
                                        <p class="js-title">
                                            <a href="#">社团类型:{{ field.community.community_type.name }}</a>
                                        </p>
                                        {#                                        <p class="js-title">#}
                                        {#                                            <a href="#">处理进度:{{ field.book.userinfo.username }}</a>#}
                                        {#                                        </p>#}
                                    </div>
                                    <a class="cui-btn"
                                       href="{% url 'com_detail' %}?id={{ field.community.id }}">查看详情</a>
                                    <a class="cui-btn"
                                       href="{% url 'home' %}">返回首页</a>
                                </li>


                            </ul>
                            {#                        <div class="news-text-pagination">#}
                            {#                            <span class="swiper-pagination-bullet"></span><span class="swiper-pagination-bullet"></span><span#}
                            {#                                class="swiper-pagination-bullet"></span><span#}
                            {#                                class="swiper-pagination-bullet swiper-pagination-bullet-active"></span>#}
                            {#                        </div>#}
                        </div>
                    </div>

                </div>
            </div>

        {% endfor %}

    </div>
</div>

<!--jQuery框架库-->
<script src="{% static 'plugin/jquery-3.4.1/jquery-3.4.1.min.js' %}"></script>

<!--插件-->
<script src="{% static 'others/js/jquery.SuperSlide.2.1.3.js' %}" type="text/javascript" charset="utf-8"></script>

<!--调用方法-->
<script type="text/javascript">
    jQuery(".news-text").slide({
        mainCell: ".news-text-content ul",
        autoPlay: false,
        titCell: ".news-text-pagination span",
        trigger: "click",
        effect: "left"
    });
</script>

</body>
</html>